require File.join(File.dirname(`node --print "require.resolve('expo/package.json')"`), "scripts/autolinking")

project 'MobilePlatform',
        'Debug' => :debug,
        'Release' => :release,
        'Debug (Prod)' => :debug

# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'Noice' do
  pod 'UnityAds', '4.12.0'
  pod 'IronSourceUnityAdsAdapter','4.3.40.2'

	pod 'GoogleUtilities', :modular_headers => true
  pod 'FirebaseCore', :modular_headers => true
  pod 'nanopb', :modular_headers => true
  pod 'FirebaseInstallations', :modular_headers => true
  pod 'GoogleDataTransport', :modular_headers => true
  pod 'FirebaseCoreExtension', :modular_headers => true

  use_expo_modules!
  post_integrate do |installer|
    begin
      expo_patch_react_imports!(installer)
    rescue => e
      Pod::UI.warn e
    end
  end
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  $RNFirebaseAsStaticFramework = true
  $RNFirebaseAnalyticsEnableAdSupport = true

  target 'Noice (STG)' do
    inherit! :complete
  end

  ENVFILES = {
    'Debug' => '$(PODS_ROOT)/../../envs/stg.env',
    'Debug (Prod)' => '$(PODS_ROOT)/../../envs/prod.env',
    'Release' => '$(PODS_ROOT)/../../envs/prod.env',
  }

  # Thing is, Firebase is going to cause some problems with dynamic frameworks
  # so every time you run into problems with pod install, check if you need to add the dep here
  pre_install do |installer|
    $dynamic_frameworks = [
      'ChargebeeReactNative',
      'Singular-React-Native',
      'WebRTC'
    ]
    installer.pod_targets.each do |pod|
      if $dynamic_frameworks.include?(pod.name)
        puts "Overriding the build_type method for #{pod.name}"
        def pod.build_type;
          BuildType.new(:linkage => :static)
        end
      end
    end
  end

  post_install do |installer|
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )

    installer.pods_project.targets.each do |target|
      # We need to remove React from the pods project because
      # it is already in the main project, and including it twice
      # causes React to run twice (hence debug menu and etc. not working)
      if target.name == 'React'
        target.remove_from_project
      end

      target.build_configurations.each do |config|
        if target.name == 'react-native-config'
          config.build_settings['ENVFILE'] = ENVFILES[config.name]
        end
      end
    end
  end
end
