export const AON_DECISION_DURATION = 15 * 1000;
export const UNSPECIFIED_CARD = 'UNSPECIFIED';
export const CARD_DEALING_ANIMATION_DURATION_PER_CARD = 100;
export const CARD_ROW_HIGHLIGHT_MINIMUM_DURATION = 3500;
export const PLAYER_SCORE_ANIMATION_DURATION = 500;
export const MOUSE_IS_LEAVING_TRANSFORM_TRANSITION = 300;
export const SIZE_TRANSITION = 75;
