export const MAXIMUM_ALLOWED_GRAPHICS_INSTANCE_COUNT = 2;

export const TARGET_BASELINE_FRAMES_PER_SECOND = 60.0;

export const FRAME_LIMITER_THRESHOLD = 0.3;

export const FRAME_LIMITER_FREQUENCY = 1.0;

export const ANALYTICS_COUNTER_FREQUENCY = 1.0;
